#ifndef LIBKLUSTERSSHARED3_GLOBAL_H
#define LIBKLUSTERSSHARED3_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBKLUSTERSSHARED3_LIBRARY)
#  define LIBKLUSTERSSHARED3SHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBKLUSTERSSHARED3SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBKLUSTERSSHARED3_GLOBAL_H
